Added System Test Bed / Node crash testing
ChrisScianna/ROS-Underwater-RnD pull request #10
Opened 2020-10-02 18:15 UTC by patapufate

Added system_test_bed package for testing
- Added node crash test for each node.

to run a particular test use:
`rostest system_test_bed test_node_crashes_thruster.test`

to run all tests
catkin_make run_tests --only-pkg-with-deps system_test_bed

2020-10-02 18:31 UTC, hidmic requested changes

2020-10-02 18:31 UTC, hidmic commented on system_test_bed/CMakeLists.txt
> +)
@patapufate it doesn't seem like you're generating messages?

2020-10-02 18:31 UTC, hidmic commented on health_monitor/include/health_monitor.h
> +        {"thruster_control_node", health_monitor::ReportFault::THRUSTER_NODE_DIED},
@patapufate this should be in its own PR. Also, we need to come up with a better way to do this mapping at some point.

2020-10-02 18:31 UTC, hidmic commented on system_test_bed/launch/fullSystem.launch
> +</launch>
@patapufate I don't think this is the right place for a full system launch nor we should replicate it.

2020-10-02 18:31 UTC, hidmic commented on system_test_bed/test/test_node_crashes.py
> +        os.system(cmd)
@patapufate consider using `os.kill` and `rosgraph` API instead of deferring calls to a shell like this.

2020-10-02 18:31 UTC, hidmic commented on system_test_bed/test/test_node_crashes.py
> +    }
@patapufate consider getting both node name and fault name from arguments instead.

2020-10-02 18:31 UTC, hidmic commented on system_test_bed/test/test_node_crashes_vectornav.test
> +  <test test-name="test_node_crashes_vectornav" pkg="system_test_bed" type="test_node_crashes.py" args="thruster_control_node_vectornav">
@patapufate typo:
```suggestion
  <test test-name="test_node_crashes_vectornav" pkg="system_test_bed" type="test_node_crashes.py" args="vectornav">
```

2020-10-05 11:44 UTC, closed without merging

2020-10-05 11:44 UTC, patapufate commented
After office discussion, we'll implement in a different way